<?php
// Generates a PDF sale order report using FPDF, with the MJ Traders logo.
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../vendor/autoload.php';
require_login();

$id = (int)($_GET['id'] ?? 0);
if ($id <= 0) { http_response_code(400); die('Invalid order id.'); }

$stmt = $pdo->prepare('SELECT * FROM sale_orders WHERE id = ?');
$stmt->execute([$id]);
$order = $stmt->fetch();
if (!$order) { http_response_code(404); die('Order not found.'); }

$items = $pdo->prepare('SELECT * FROM sale_order_items WHERE sale_order_id = ?');
$items->execute([$id]);
$items = $items->fetchAll();

$config = require __DIR__ . '/../config/app.php';
$logoPath = __DIR__ . '/../public/assets/mj-traders.png';

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 15);
$pdf->SetMargins(15, 15, 15);

$pageW = $pdf->GetPageWidth() - 30;

// Header: logo + company
if (file_exists($logoPath)) {
    $pdf->Image($logoPath, 15, 12, 35);
}
$pdf->SetXY(55, 14);
$pdf->SetFont('Arial', 'B', 18);
$pdf->Cell(0, 9, 'MJ Traders', 0, 1);
$pdf->SetX(55);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 6, 'Inventory & Sales Management', 0, 1);
$pdf->SetX(55);
$pdf->Cell(0, 6, 'Sale Order / Tax Invoice', 0, 1);
$pdf->Ln(4);

// Order meta (right aligned)
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(0, 7, 'Order No: ' . $order['order_no'], 0, 1, 'R');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 6, 'Date & Time: ' . $order['order_date'], 0, 1, 'R');
$pdf->Ln(2);

// Divider
$pdf->SetDrawColor(200);
$pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
$pdf->Ln(4);

// Customer details box
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(0, 7, 'Customer Details', 0, 1);
$pdf->SetFont('Arial', '', 10);
$cust = [
    'Customer Code' => $order['customer_code'],
    'Customer Name' => $order['customer_name'],
    'Contact'       => $order['contact'],
    'Delivery Route'=> $order['delivery_route'],
    'Sales Man'     => $order['salesman'],
    'NTN No'        => $order['ntn_no'],
    'Sales Tax No'  => $order['sales_tax_no'],
    'CNIC'          => $order['cnic'],
    'Address'       => $order['address'],
];
$left = array_slice($cust, 0, 5, true);
$right = array_values(array_slice($cust, 5, null, true));
$leftKeys = array_keys($left);
foreach ($leftKeys as $i => $k) {
    $rKey = $right[$i][0] ?? '';
    $rVal = $right[$i][1] ?? '';
    $pdf->Cell(45, 6, $k . ':', 0, 0);
    $pdf->Cell(60, 6, (string)$left[$k], 0, 0);
    $pdf->Cell(35, 6, $rKey . ':', 0, 0);
    $pdf->Cell(0, 6, (string)$rVal, 0, 1);
}
$pdf->Ln(3);

// Items table
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(240);
$cols = [['#', 10], ['Product', 80], ['Qty', 20], ['Price', 35], ['Line Total', 40]];
foreach ($cols as $c) { $pdf->Cell($c[1], 7, $c[0], 1, 0, 'C', true); }
$pdf->Ln();
$pdf->SetFont('Arial', '', 10);
$i = 1;
foreach ($items as $it) {
    $pdf->Cell(10, 7, $i++, 1, 0, 'C');
    $pdf->Cell(80, 7, $it['product_name'], 1, 0, 'L');
    $pdf->Cell(20, 7, $it['quantity'], 1, 0, 'C');
    $pdf->Cell(35, 7, number_format($it['price'], 2), 1, 0, 'R');
    $pdf->Cell(40, 7, number_format($it['line_total'], 2), 1, 1, 'R');
}

// Totals
$pdf->Ln(2);
$pdf->SetFont('Arial', '', 10);
$rightX = 145;
$pdf->Cell($rightX, 7, 'Subtotal', 0, 0, 'R');
$pdf->Cell(40, 7, number_format($order['subtotal'], 2), 1, 1, 'R');

$pdf->Cell($rightX, 7, 'Sales Tax (' . $order['sales_tax_pct'] . '%)', 0, 0, 'R');
$pdf->Cell(40, 7, number_format($order['sales_tax_amt'], 2), 1, 1, 'R');

$pdf->Cell($rightX, 7, 'GST (' . $order['gst_pct'] . '%)', 0, 0, 'R');
$pdf->Cell(40, 7, number_format($order['gst_amt'], 2), 1, 1, 'R');

$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell($rightX, 8, 'Net Total', 0, 0, 'R');
$pdf->Cell(40, 8, number_format($order['total'], 2), 1, 1, 'R');

$pdf->Ln(10);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(0, 6, 'Generated by MJ Traders Inventory System', 0, 1, 'C');

if (ob_get_length()) ob_clean();
$pdf->Output('I', 'SaleOrder-' . $order['order_no'] . '.pdf');
